name: Build and Package (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_linux:
    name: Build (Ubuntu)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          libgl1-mesa-dev \
          wget \
          patchelf

    - name: Install Qt
      run: |
        python -m pip install aqtinstall
        python -m aqt install-qt linux desktop 6.6.3 gcc_64 \
          --outputdir "$HOME/Qt" \
          --modules qtbase qttools

    - name: Configure CMake
      run: |
        cmake -B build \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH="$HOME/Qt/6.6.3/gcc_64"

    - name: Build
      run: |
        cmake --build build --config Release --parallel $(nproc)

    - name: Create AppImage
      run: |
        mkdir -p package/usr/{bin,lib}
        cp build/MyProject package/usr/bin/
        
        # Copy dependencies
        ldd package/usr/bin/MyProject | grep "=> /" | awk '{print $3}' | xargs -I '{}' cp -v '{}' package/usr/lib/
        
        # Create desktop file
        cat > package/MyProject.desktop <<EOF
        [Desktop Entry]
        Name=MyProject
        Exec=MyProject
        Icon=MyProject
        Type=Application
        Categories=Utility;
        EOF
        
        # Download appimagetool
        wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        ./appimagetool-x86_64.AppImage package MyProject-Linux.AppImage

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyProject-Linux
        path: MyProject-Linux.AppImage
