name: Build LionCPP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            qt_version: '6.6.3'  # 改用LTS版本确保稳定性
            build_dir: build
            generator: "Ninja"
            artifact_name: LionCPP-Linux
            qt_arch: "gcc_64"
            setup_script: |
              sudo apt-get update
              sudo apt-get install -y build-essential cmake ninja-build libgl1-mesa-dev
          
          - os: windows-latest
            qt_version: '6.6.3'
            build_dir: build
            generator: "Ninja"
            artifact_name: LionCPP-Windows
            qt_arch: "win64_msvc2022_64"
            setup_script: |
              choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
              choco install ninja
              refreshenv
          
          - os: macos-latest
            qt_version: '6.6.3'
            build_dir: build
            generator: "Ninja"
            artifact_name: LionCPP-macOS
            qt_arch: "clang_64"
            setup_script: |
              brew install cmake ninja

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build tools
      run: ${{ matrix.setup_script }}

    - name: Install aqtinstall
      run: |
        python -m pip install --upgrade pip
        python -m pip install aqtinstall==3.1.21

    - name: Debug Qt installation options
      run: |
        echo "=== Correct command to list Qt versions ==="
        python -m aqt list-qt linux desktop
        
        echo "=== Available architectures ==="
        python -m aqt list-qt linux desktop --arch ${{ matrix.qt_version }}
        
        echo "=== Testing module availability ==="
        python -m aqt list-qt linux desktop --modules ${{ matrix.qt_version }} ${{ matrix.qt_arch }} || echo "Module query failed"

    - name: Install Qt
      run: |
        # 使用保守安装方式
        python -m aqt install-qt \
          ${{ matrix.os == 'windows-latest' && 'windows' || matrix.os == 'macos-latest' && 'mac' || 'linux' }} \
          desktop \
          ${{ matrix.qt_version }} \
          ${{ matrix.qt_arch }} \
          --outputdir "$HOME/Qt" \
          --modules qtbase

    - name: Verify Qt installation
      run: |
        QT_ROOT="$HOME/Qt/${{ matrix.qt_version }}/${{ matrix.qt_arch }}"
        echo "QT_PATH=${QT_ROOT}" >> $GITHUB_ENV
        
        if [ -f "$QT_ROOT/bin/qmake" ]; then
          echo "Qt installation verified:"
          "$QT_ROOT/bin/qmake" -v
        else
          echo "::error::Qt installation failed!"
          ls -la "$QT_ROOT/bin" || true
          exit 1
        fi

    # 后续构建步骤保持不变...
    - name: Configure CMake
      shell: bash
      run: |
        mkdir -p ${{ matrix.build_dir }}
        cd ${{ matrix.build_dir }}
        cmake .. \
          -G "${{ matrix.generator }}" \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH="$QT_PATH"

    - name: Build
      shell: bash
      run: |
        cd ${{ matrix.build_dir }}
        cmake --build . --config Release --parallel $(nproc)

    # 打包和上传步骤...
